# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Josh Stewart
description: personal blog
url: http://lightergrey.github.io

# Same as the title etc for your site but can instead be
# called by using 'site.owner.name' and so on
owner:
  name: Josh Stewart

exclude: [Gemfile, Gemfile.lock, gulpfile.js, node_modules, package.json, README.md]
permalink: /:title
paginate: 5
paginate_path: "page/:num"
highlighter: pygments
